# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app102974301

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a8f8123aaac24d2cbd38bab49b315172 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_27c200923d834bebb543805cf0405bc4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a8f8123aaac24d2cbd38bab49b315172 }}/jkudo/demohaproxy:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app102974301'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_96292499a88d4e59a79143123cf6d83c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a8f8123aaac24d2cbd38bab49b315172 }}/jkudo/demohaproxy:${{ github.sha }}'